In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
!wget https://raw.githubusercontent.com/gauravpks/ml-repo/master/Part%201%20-%20Data%20Preprocessing/sbux_mv.csv

--2020-12-08 17:27:46--  https://raw.githubusercontent.com/gauravpks/ml-repo/master/Part%201%20-%20Data%20Preprocessing/sbux_mv.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62806 (61K) [text/plain]
Saving to: ‘sbux_mv.csv’

sbux_mv.csv         100%[===================>]  61.33K  --.-KB/s    in 0.004s  

2020-12-08 17:27:46 (16.3 MB/s) - ‘sbux_mv.csv’ saved [62806/62806]



In [3]:
missing_values = ['na','--','N/A','NA',' ']

In [4]:
df = pd.read_csv('sbux_mv.csv',na_values=missing_values).iloc[:,:-1]
df

date    open    high     low   close    volume
0     08-02-2013  27.920  28.325  27.920  28.185   7146296
1     11-02-2013  28.260  28.260  27.930  28.070   5457354
2     12-02-2013  28.000  28.275  27.975  28.130   8665592
3     13-02-2013  28.230  28.230  27.750  27.915   7022056
4     14-02-2013  27.765  27.905  27.675  27.775   8899188
...          ...     ...     ...     ...     ...       ...
1254  01-02-2018  56.280  56.420  55.890  56.000  14690146
1255  02-02-2018  55.900  56.320  55.700  55.770  15358909
1256  05-02-2018  55.530  56.260  54.570  54.690  16059955
1257  06-02-2018  53.685  56.060  53.560  55.610  17415065
1258  07-02-2018  55.080  55.430  54.440  54.460  13927022

[1259 rows x 6 columns]

In [5]:
df.isnull().sum()

date      0
open      1
high      5
low       1
close     2
volume    0
dtype: int64

In [6]:
x = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [7]:
x

array([[27.92 , 28.325, 27.92 , 28.185],
       [28.26 , 28.26 , 27.93 , 28.07 ],
       [28.   , 28.275, 27.975, 28.13 ],
       ...,
       [55.53 , 56.26 , 54.57 , 54.69 ],
       [53.685, 56.06 , 53.56 , 55.61 ],
       [55.08 , 55.43 , 54.44 , 54.46 ]])

In [8]:
y

array([ 7146296,  5457354,  8665592, ..., 16059955, 17415065, 13927022])

In [9]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values=np.nan, strategy = 'mean')
si.fit(x[:,1:])
x[:,1:]= si.transform(x[:,1:])

In [10]:
x

array([[27.92 , 28.325, 27.92 , 28.185],
       [28.26 , 28.26 , 27.93 , 28.07 ],
       [28.   , 28.275, 27.975, 28.13 ],
       ...,
       [55.53 , 56.26 , 54.57 , 54.69 ],
       [53.685, 56.06 , 53.56 , 55.61 ],
       [55.08 , 55.43 , 54.44 , 54.46 ]])

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)

In [12]:
x_train

array([[29.845, 29.985, 29.565, 29.915],
       [60.65 , 60.81 , 60.02 , 60.03 ],
       [57.93 , 58.5  , 57.76 , 58.44 ],
       ...,
       [59.89 , 60.16 , 59.47 , 60.14 ],
       [37.77 , 38.165, 37.705, 38.095],
       [61.63 , 61.94 , 61.19 , 61.3  ]])

In [13]:
print(len(x_test))

252


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
x_test

array([[0.92052402, 0.88151365, 0.92251911, 0.88421428],
       [1.14405959, 1.11588612, 1.1125855 , 1.14474386],
       [0.80343396, 0.76866765, 0.79483348, 0.75733928],
       ...,
       [0.83246456, 0.82846639, 0.87037269, 0.85419043],
       [0.58763989, 0.56515905, 0.572602  , 0.60044043],
       [0.75698501, 0.77156114, 0.79288408, 0.78542611]])

In [19]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

ValueError: ignored