<a href="https://colab.research.google.com/github/vivek-varshney/Practice/blob/main/ML/SVR_ML_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df  = pd.read_csv('https://raw.githubusercontent.com/gauravpks/ml-repo/master/Part%202%20-%20Regression/Support%20Vector%20Regression%20(SVR)/Position_Salaries.csv')
df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [3]:
X=df.iloc[:,1].values
y =df.iloc[:,-1].values

In [4]:
X = X.reshape(len(X),1)
y = y.reshape(len(y),1)

In [5]:
np.shape(X)

(10, 1)

In [6]:
y

array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]])

In [7]:
np.shape(y)

(10, 1)

In [8]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()

X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [9]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X,y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [15]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[6.5]])))

array([170370.0204065])

In [12]:
sc_y.inverse_transform(regressor.predict(sc_X.transform(X)))

array([180739.65882955, 164073.87510693, 146532.06498588, 128932.77287841,
       112202.31688308,  97274.49008769,  84978.38902116,  75933.62771109,
        70471.95091295,  68599.42219624])